image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker version
  - docker-compose version

test:
  cache:
    paths:
      - vendor/
  script:
    - docker-compose build tests/docker-compose.yml
    - docker-compose run -f tests/docker-compose.yml --rm debian
