---
- name: set os-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: determine if proxmox is installed
  package_facts:
    manager: "auto"
  tags: network

- name: set the list of dynamic packages
  set_fact:
    dubzland_networking_dynamic_packages: "{{ lookup('template', 'lookups/_network_dynamic_packages.j2', convert_data=False) | from_yaml }}"

- name: assemble list of packages to be installed
  set_fact:
    dubzland_networking_packages_combined: '{{
      dubzland_networking_base_packages |
      union(dubzland_networking_dynamic_packages) |
      union(dubzland_networking_packages) | unique
    }}'
  tags: network
