---
dubzland_networking_base_packages:
  - iproute2
  - bsdutils
  - rsync

dubzland_networking_interface_weights: {
  "eth": '10',
  "bond": '20',
  "bridge": '30',
  "ucarp": '40',
  "vlan": '50'
}
