---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-networking
      vars:
        dubzland_networking_interfaces:
          - name: eth1
            type: eth
            inet: static
            address: 10.1.1.2/24
            gateway: 10.1.1.1
