---
- name: Prepare
  hosts: all
  tasks:
    - name: update the apt cache
      apt:
        update_cache: True
      when: ansible_os_family == 'Debian'
    - name: install ifupdown2
      apt:
        name: ifupdown2
        state: present
      when: ansible_os_family == 'Debian'
